Update to SDL3 (#15)
* S⭐D⭐L⭐3 (tiny little refactor😋)

* keyboard fixes

* pick a renderer

* "palm rejection"

* update meson wraps

* "Temporary failure in name resolution"

* Revert "update meson wraps"

This reverts commit d766f9d490687e8e2537c99603de9c9a9791b969.

* double click to wand select

* render palette colors

* day 1 of fixing d3d11/12

* day 500 of fighting with windows ink

* windows ink kind of fixed

* Update maineditor.cpp

* mouse movement zoom (middle+left click)

* restyle navbar for readability

* allow some restricted keybinds to be used

* fix lmu to image render...... 💀

* setup to autoload relevant subscreens with files

* preview screen on hover

* add hsl

* add ycbcr, fix hsl sliders

* hsv sliders hue preview, deprecate uihueslider

* delete to clear whole layer or selected area

* automatic recovery autosaves

* keep track of recovery autosave

* mark unsaved changes on undo/redo

* [refactor] separate rpgm io

* initial quantize impl.

* keep alpha (0 or 255) on quantize

* add reference image + fix memleak

* battery indicator

* (WIP) SDL3: Linux support (#16)

* io_aseprite: do not return NULL in bool function

Fixes the following error:

../freesprite/io_aseprite.cpp: In function 'bool writeAsepriteASE(std::string, MainEditor*)':
../freesprite/io_aseprite.cpp:282:20: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]

* mathops: include math.h

Fixes the following error:

../freesprite/mathops.h: In constructor 'Bitblock::Bitblock(uint64_t)':
../freesprite/mathops.h:140:32: error: 'ceill' was not declared in this scope

* maineditor: fix autosave timer compilation on non-windows platforms

* meson: fix sdl3_dep variables being named sdl2

* meson: drop sdl2 wraps

* flatpak: add SDL3

* mac sdl3 + temporarily disable linux portable build

* mac

* update readme [no ci]

---------

Co-authored-by: knuxify <knuxify@gmail.com>